// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvlDfHn5i5dThcRvPInAqyh6G619eibI',
    appId: '1:1056713918058:android:5061e7a59dd28290b96c13',
    messagingSenderId: '1056713918058',
    projectId: 'farmhouse-bfefe',
    storageBucket: 'farmhouse-bfefe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCavmLwBen5Pvtwk16ljZlPPIQ9H47e7ys',
    appId: '1:1056713918058:ios:1c5402b4b612070fb96c13',
    messagingSenderId: '1056713918058',
    projectId: 'farmhouse-bfefe',
    storageBucket: 'farmhouse-bfefe.appspot.com',
    iosBundleId: 'com.example.farmLoanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJXD-0wWqXU5fpwoDxDvcZytAfhhhB4FI',
    appId: '1:1056713918058:web:0344e59290e3643db96c13',
    messagingSenderId: '1056713918058',
    projectId: 'farmhouse-bfefe',
    authDomain: 'farmhouse-bfefe.firebaseapp.com',
    storageBucket: 'farmhouse-bfefe.appspot.com',
  );
}
